### ISSUE TITLE
Docker amd64 unable to build with ruby 3.3.0 - nokogiri 1.16.0 fails to install with libjemalloc2 libjemalloc-dev debian deps installed

### ISSUE THREAD

**Issue by mandros1985** [jemalloc/jemalloc#2595]
Please tell me what can I fix in my dockerfile to make this build with jemalloc 

my local dev.Dockerfile 

```
FROM ruby:3.3.0-bookworm

ENV APP_HOME=/app \
#    LD_PRELOAD="libjemalloc.so.2" \
#    MALLOC_CONF="dirty_decay_ms:1000,narenas:2,background_thread:true,stats_print:true" \
    RUBY_YJIT_ENABLE="1" \
    LANG=C.UTF-8 \
    RUBY_VERSION=3.3.0 \
    BUNDLER_VERSION=2.5.4 \
    CHAMBER_VERSION=2.13.6 \
    NODE_VERSION=20 \
    BUNDLE_PATH=/bundle \
    BUNDLE_BIN=/bundle/bin \
    GEM_HOME=/bundle \
    RAILS_ENV=development \
    BUNDLE_GITLAB__COM=change_me \
    BUNDLE_GITHUB__COM=change_me
#libjemalloc2 libjemalloc-dev
# dose not work with jemalloc deps - had to remove it for now TODO: fix it

RUN apt-get update -qq \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y wget nano zlib1g-dev liblzma-dev patch pkg-config

RUN wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add -
RUN echo "deb http://apt.postgresql.org/pub/repos/apt bookworm-pgdg main" |tee  /etc/apt/sources.list.d/pgdg.list

RUN apt-get update -qq \
    && curl -fsSL https://deb.nodesource.com/setup_$NODE_VERSION.x | bash - \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends nodejs

RUN apt-get update -qq \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends libxml2-dev nano libxslt-dev git tzdata unzip openssl postgresql-client libjpeg62 libpng-dev libxrender1 libxext-dev wkhtmltopdf libfontconfig1 libssl-dev

RUN wget -q -O /bin/chamber https://github.com/segmentio/chamber/releases/download/v$CHAMBER_VERSION/chamber-v${CHAMBER_VERSION}-linux-amd64
RUN chmod +x /bin/chamber \
    && rm -rf /var/lib/apt/lists/* \
    && sed -i 's,^\(MinProtocol[ ]*=\).*,\1'TLSv1.0',g' /etc/ssl/openssl.cnf \
    && sed -i 's,^\(CipherString[ ]*=\).*,\1'DEFAULT@SECLEVEL=1',g' /etc/ssl/openssl.cnf

# install latest chrome for testing purposes
RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - \
    && echo 'deb http://dl.google.com/linux/chrome/deb/ stable main' >> /etc/apt/sources.list.d/google.list
RUN apt-get update && apt-get -y install google-chrome-stable

#RUN wget -q http://archive.ubuntu.com/ubuntu/pool/main/o/openssl/openssl_1.1.1f-1ubuntu2.20_amd64.deb \
#    && yes | dpkg -i ./openssl_1.1.1f-1ubuntu2.20_amd64.deb
# old deps - left fpr refference

RUN mkdir ${APP_HOME}
WORKDIR ${APP_HOME}
RUN gem install bundler:$BUNDLER_VERSION
RUN bundle config set --global force_ruby_platform true
COPY Gemfile $APP_HOME/
COPY Gemfile.lock $APP_HOME/
RUN bundle install -j40 --retry 30 \
    && bundle check || bundle install
COPY . ${APP_HOME}
```

**Comment by mandros1985** [comment]
using also docker compose 

```
version: "3.9"
services:
  app:
    platform: linux/x86_64
    build:
      context: .
      
      ... TLDR

```

**Comment by mandros1985** [comment]
When build as is the nokogiri inside the image is 

```

root@c830f01b9add:/app# bundle exec nokogiri --version
# Nokogiri (1.16.0)
    ---
    warnings: []
    nokogiri:
      version: 1.16.0
      cppflags:
      - "-I/bundle/ruby/3.3.0/gems/nokogiri-1.16.0/ext/nokogiri"
      - "-I/bundle/ruby/3.3.0/gems/nokogiri-1.16.0/ext/nokogiri/include"
      - "-I/bundle/ruby/3.3.0/gems/nokogiri-1.16.0/ext/nokogiri/include/libxml2"
      ldflags: []
    ruby:
      version: 3.3.0
      platform: x86_64-linux
      gem_platform: x86_64-linux
      description: ruby 3.3.0 (2023-12-25 revision 5124f9ac75) +YJIT [x86_64-linux]
      engine: ruby
    libxml:
      source: packaged
      precompiled: false
      patches:
      - 0001-Remove-script-macro-support.patch
      - 0002-Update-entities-to-remove-handling-of-ssi.patch
      - 0003-libxml2.la-is-in-top_builddir.patch
      - '0009-allow-wildcard-namespaces.patch'
      - 0010-update-config.guess-and-config.sub-for-libxml2.patch
      - 0011-rip-out-libxml2-s-libc_single_threaded-support.patch
      memory_management: ruby
      iconv_enabled: true
      compiled: 2.12.3
      loaded: 2.12.3
    libxslt:
      source: packaged
      precompiled: false
      patches:
      - 0001-update-config.guess-and-config.sub-for-libxslt.patch
      datetime_enabled: true
      compiled: 1.1.39
      loaded: 1.1.39
    other_libraries:
      libgumbo: 1.0.0-nokogiri
```
